# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: GuepardoApps
name: Jonas Schubert
menu_right_subtitle: Medical software engineer
avatar: http://api.adorable.io/avatar/gueparodapps
logo: static/img/logo.png
email: guepardoapps@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Website for GuepardoApps hosted on GuepardoApps.
  Free repositories with MIT license for your personal use.
  Mostly home automation, password safe and more.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://guepardoapps.github.io/" # the base hostname & protocol for your site
permalink: /posts/:title

github_username: GuepardoApps

theme: jekyll-theme-cayman 